# Generated by Django 6.0.1 on 2026-01-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('win_rate', models.FloatField()),
                ('total_pnl_pct', models.FloatField()),
                ('total_trades', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.CharField(default='SPY', max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('pnl_val', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField()),
            ],
        ),
    ]
