# Generated by Django 6.0.1 on 2026-01-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('prediction', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('expected_move_pct', models.FloatField(blank=True, null=True)),
                ('option_strike', models.FloatField(blank=True, null=True)),
                ('option_premium', models.FloatField(blank=True, null=True)),
                ('option_expiry', models.CharField(blank=True, max_length=20, null=True)),
                ('option_type', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_price', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('position_size', models.FloatField()),
                ('result', models.CharField(max_length=20)),
                ('pnl_pct', models.FloatField()),
                ('pnl_val', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
